services:
  - type: web
    name: smartprice
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python backend/train_model.py
    startCommand: gunicorn --chdir backend app:app
    autoDeploy: true
